#!/usr/bin/env bash

datetime=$(date +'%D  %I:%M %P')

charge_status=$(cat /sys/class/power_supply/BAT0/status)
charge_percent=$(cat /sys/class/power_supply/BAT0/capacity)
volume_percent=$(amixer get Master | grep "Right:" | cut -f 7 -d " "| sed 's/[][]//g')
mute_status=$(amixer get Master | grep "Right:" | cut -f 8 -d " "| sed 's/[][]//g')

if [ $mute_status == 'on' ]; then
    mute_icon=
else
    mute_icon=
fi

if [ $charge_status == 'Charging' ]; then
	status_icon=󰂉
else
	status_icon=󰂀
fi

echo ' | '$datetime' | ' $mute_icon'  '$volume_percent' | ' $status_icon' '$charge_percent"%  "
