#!/usr/bin/env bash

# Basic status bar for sway using PulseAudio, iwd

SEP=" | "
PAD=" "

get_network() {
    if [[ $(iwgetid) ]]; then
        wifi_icon="󰖩 "
        ssid="$(iwgetid -r)"
    else
        wifi_icon="󰖪 "
        ssid=" "
    fi
    network="$wifi_icon$PAD$ssid"
}

get_volume() {
    vol=$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | grep -oP '\d+(?=%)' | head -1)
    muted=$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | awk '{print $2}')

    if [ "$muted" = "yes" ]; then
        volume_icon="  "
    else
        volume_icon="  "
    fi
    volume="$volume_icon$PAD$vol%"
}

get_battery() {
    charge_status=$(cat /sys/class/power_supply/BAT0/status)
    charge_percent=$(cat /sys/class/power_supply/BAT0/capacity)

    if [ "$charge_status" == 'Charging' ]; then
        charge_icon="󰂉 "
    else
        charge_icon="󰂀"
    fi
    battery="$charge_icon$PAD$charge_percent%"
}

get_datetime() {
    datetime=$(date +'%D  %I:%M %P')
}

output() {
    get_network
    get_volume
    get_battery
    get_datetime
    echo "$network${SEP}$volume${SEP}$battery${SEP}$datetime$PAD"
}

output
