# Tmux Settings
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
setw -g aggressive-resize on
set -as terminal-features "xterm-256color:RGB"
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# Plugin Loading
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jpnski/dracula-tmux-nord'

# Define Nord Colors
set -g @dracula-colors "
nord_frost1='#8FBCBB' nord_frost2='#88C0D0' nord_frost3='#81A1C1' nord_frost4='#5E81AC'
nord_dark1='#4C566A' nord_dark2='#434C5E' nord_dark3='#3B4252' nord_dark4='#2E3440' nord_dark5='#242933'
aurora_red='#BF616A' aurora_orange='#D08770' aurora_green='#A3BE8C' aurora_purple='#B48EAD'
"

# Nord Re-coloring
set -g @dracula-powerline-bg        "nord_dark4"
set -g @dracula-window-title-fg     "nord_frost2"

set -g @dracula-left-icon-bg        "nord_dark3"
set -g @dracula-left-icon-fg        "nord_frost1"

set -g @dracula-left-icon-prefix-bg "aurora_orange"
set -g @dracula-left-icon-prefix-fg "nord_dark4"

set -g @dracula-active-window-bg    "aurora_purple"
set -g @dracula-active-window-fg    "nord_dark4"

set -g @dracula-inactive-window-bg  "nord_dark1"
set -g @dracula-inactive-window-fg  "nord_frost2"

set -g @dracula-git-colors          "nord_dark1 nord_frost3"
set -g @dracula-cpu-usage-colors    "nord_dark2 nord_frost3"
set -g @dracula-ram-usage-colors    "nord_dark3 nord_frost3"

# Visual Elements
set -g @dracula-show-flags true
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon laptop
set -g @dracula-plugins "git cpu-usage ram-usage"

# Git Icons
set -g @dracula-git-no-repo-message 󱓌
set -g @dracula-git-show-current-symbol 
set -g @dracula-git-show-diff-symbol 󱓊

# Last Line
run '~/.tmux/plugins/tpm/tpm'
